version: '3'
services:
  database:
    image: bitnami/postgresql
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=cardapio
